accessing
jsonFaceLandmarksEinstein
	^ STONJSON fromString: '{
			"noseRootRight" : {
				"x" : 912.4,
				"y" : 347.8
			},
			"eyeLeftTop" : {
				"x" : 887.4,
				"y" : 345.3
			},
			"eyebrowLeftInner" : {
				"x" : 897.1,
				"y" : 340.6
			},
			"upperLipTop" : {
				"x" : 911.1,
				"y" : 392.4
			},
			"noseRightAlarOutTip" : {
				"x" : 921.5,
				"y" : 374.2
			},
			"noseRootLeft" : {
				"x" : 900.6,
				"y" : 349.4
			},
			"noseTip" : {
				"x" : 907.2,
				"y" : 373.9
			},
			"pupilLeft" : {
				"x" : 888.1,
				"y" : 348.5
			},
			"mouthRight" : {
				"x" : 931.5,
				"y" : 393.9
			},
			"pupilRight" : {
				"x" : 929.6,
				"y" : 344.3
			},
			"eyeRightInner" : {
				"x" : 922.0,
				"y" : 346.2
			},
			"noseRightAlarTop" : {
				"x" : 916.2,
				"y" : 365.0
			},
			"eyeRightBottom" : {
				"x" : 929.7,
				"y" : 349.3
			},
			"eyeLeftOuter" : {
				"x" : 881.7,
				"y" : 350.7
			},
			"eyebrowRightOuter" : {
				"x" : 944.3,
				"y" : 336.7
			},
			"eyeLeftInner" : {
				"x" : 895.1,
				"y" : 348.9
			},
			"underLipBottom" : {
				"x" : 912.5,
				"y" : 402.6
			},
			"eyebrowRightInner" : {
				"x" : 913.1,
				"y" : 337.5
			},
			"eyeLeftBottom" : {
				"x" : 888.7,
				"y" : 352.8
			},
			"eyeRightTop" : {
				"x" : 928.7,
				"y" : 341.4
			},
			"noseLeftAlarOutTip" : {
				"x" : 895.8,
				"y" : 377.1
			},
			"upperLipBottom" : {
				"x" : 911.4,
				"y" : 396.0
			},
			"mouthLeft" : {
				"x" : 894.9,
				"y" : 396.1
			},
			"eyeRightOuter" : {
				"x" : 936.3,
				"y" : 344.9
			},
			"underLipTop" : {
				"x" : 911.4,
				"y" : 397.1
			},
			"eyebrowLeftOuter" : {
				"x" : 870.7,
				"y" : 346.5
			},
			"noseLeftAlarTop" : {
				"x" : 900.3,
				"y" : 366.8
			}
		}'
	

