accessing
jsonFaceLandmarksSolovine
	^ STONJSON fromString: '{
			"noseRootRight" : {
				"x" : 673.8,
				"y" : 199.8
			},
			"eyeLeftTop" : {
				"x" : 642.4,
				"y" : 197.3
			},
			"eyebrowLeftInner" : {
				"x" : 657.8,
				"y" : 192.6
			},
			"upperLipTop" : {
				"x" : 671.3,
				"y" : 236.3
			},
			"noseRightAlarOutTip" : {
				"x" : 683.5,
				"y" : 219.5
			},
			"noseRootLeft" : {
				"x" : 661.8,
				"y" : 201.0
			},
			"noseTip" : {
				"x" : 671.2,
				"y" : 220.5
			},
			"pupilLeft" : {
				"x" : 642.6,
				"y" : 199.2
			},
			"mouthRight" : {
				"x" : 687.4,
				"y" : 237.3
			},
			"pupilRight" : {
				"x" : 684.9,
				"y" : 195.2
			},
			"eyeRightInner" : {
				"x" : 680.0,
				"y" : 197.3
			},
			"noseRightAlarTop" : {
				"x" : 679.2,
				"y" : 213.1
			},
			"eyeRightBottom" : {
				"x" : 686.2,
				"y" : 197.5
			},
			"eyeLeftOuter" : {
				"x" : 635.7,
				"y" : 200.9
			},
			"eyebrowRightOuter" : {
				"x" : 701.2,
				"y" : 187.0
			},
			"eyeLeftInner" : {
				"x" : 650.5,
				"y" : 199.5
			},
			"underLipBottom" : {
				"x" : 672.8,
				"y" : 247.1
			},
			"eyebrowRightInner" : {
				"x" : 673.4,
				"y" : 191.3
			},
			"eyeLeftBottom" : {
				"x" : 643.2,
				"y" : 202.4
			},
			"eyeRightTop" : {
				"x" : 685.1,
				"y" : 193.5
			},
			"noseLeftAlarOutTip" : {
				"x" : 657.7,
				"y" : 223.0
			},
			"upperLipBottom" : {
				"x" : 671.9,
				"y" : 239.8
			},
			"mouthLeft" : {
				"x" : 652.0,
				"y" : 240.4
			},
			"eyeRightOuter" : {
				"x" : 691.8,
				"y" : 195.1
			},
			"underLipTop" : {
				"x" : 671.7,
				"y" : 241.6
			},
			"eyebrowLeftOuter" : {
				"x" : 624.2,
				"y" : 196.4
			},
			"noseLeftAlarTop" : {
				"x" : 660.4,
				"y" : 216.0
			}
		}'
	

