accessing
jsonFaceLandmarksHabicht
	^ STONJSON fromString: '{
			"noseRootRight" : {
				"x" : 335.1,
				"y" : 340.8
			},
			"eyeLeftTop" : {
				"x" : 305.9,
				"y" : 335.8
			},
			"eyebrowLeftInner" : {
				"x" : 319.7,
				"y" : 329.1
			},
			"upperLipTop" : {
				"x" : 331.3,
				"y" : 379.8
			},
			"noseRightAlarOutTip" : {
				"x" : 344.1,
				"y" : 363.9
			},
			"noseRootLeft" : {
				"x" : 324.2,
				"y" : 341.0
			},
			"noseTip" : {
				"x" : 334.0,
				"y" : 361.6
			},
			"pupilLeft" : {
				"x" : 307.2,
				"y" : 338.3
			},
			"mouthRight" : {
				"x" : 345.9,
				"y" : 387.6
			},
			"pupilRight" : {
				"x" : 347.0,
				"y" : 339.4
			},
			"eyeRightInner" : {
				"x" : 340.4,
				"y" : 340.2
			},
			"noseRightAlarTop" : {
				"x" : 340.3,
				"y" : 356.1
			},
			"eyeRightBottom" : {
				"x" : 347.0,
				"y" : 342.9
			},
			"eyeLeftOuter" : {
				"x" : 299.1,
				"y" : 340.5
			},
			"eyebrowRightOuter" : {
				"x" : 360.7,
				"y" : 332.7
			},
			"eyeLeftInner" : {
				"x" : 313.7,
				"y" : 339.8
			},
			"underLipBottom" : {
				"x" : 330.5,
				"y" : 393.8
			},
			"eyebrowRightInner" : {
				"x" : 337.0,
				"y" : 330.0
			},
			"eyeLeftBottom" : {
				"x" : 306.0,
				"y" : 341.8
			},
			"eyeRightTop" : {
				"x" : 347.1,
				"y" : 336.9
			},
			"noseLeftAlarOutTip" : {
				"x" : 316.5,
				"y" : 364.5
			},
			"upperLipBottom" : {
				"x" : 330.8,
				"y" : 384.7
			},
			"mouthLeft" : {
				"x" : 309.0,
				"y" : 387.6
			},
			"eyeRightOuter" : {
				"x" : 353.7,
				"y" : 341.2
			},
			"underLipTop" : {
				"x" : 330.8,
				"y" : 388.9
			},
			"eyebrowLeftOuter" : {
				"x" : 288.0,
				"y" : 332.3
			},
			"noseLeftAlarTop" : {
				"x" : 321.6,
				"y" : 356.7
			}
		}'