Class {
	#name : #TDNullComment,
	#superclass : #TDNullModel,
	#traits : 'TGtUniqueInstance',
	#classTraits : 'TGtUniqueInstance classTrait',
	#category : #'GToolkit-Demo-TodosAPI-Core'
}

{ #category : #accessing }
TDNullComment >> body [
	^ ''.
]

{ #category : #accessing }
TDNullComment >> email [
	^ ''.
]

{ #category : #accessing }
TDNullComment >> id [
	^ 0.
]

{ #category : #accessing }
TDNullComment >> name [
	^ ''.
]

{ #category : #accessing }
TDNullComment >> postId [
	^ 0.
]
