Class {
	#name : #TDNullImage,
	#superclass : #TDNullModel,
	#traits : 'TGtUniqueInstance',
	#classTraits : 'TGtUniqueInstance classTrait',
	#category : #'GToolkit-Demo-TodosAPI-Core'
}

{ #category : #accessing }
TDNullImage >> album [
	^ nil.
]

{ #category : #accessing }
TDNullImage >> albumId [
	^ 0.
]

{ #category : #accessing }
TDNullImage >> id [
	^ 0.
]

{ #category : #accessing }
TDNullImage >> image [
	^ nil.
]

{ #category : #accessing }
TDNullImage >> thumbnail [
	^ nil.
]

{ #category : #accessing }
TDNullImage >> title [
	^ ''.
]

{ #category : #accessing }
TDNullImage >> url [
	^ ''.
]
