"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser


"
Class {
	#name : #ManifestGToolkitDemoCognitiveServicesFaceAPIExtensions,
	#superclass : #PackageManifest,
	#category : #'GToolkit-Demo-CognitiveServices-FaceAPI-Extensions'
}

{ #category : #'meta-data' }
ManifestGToolkitDemoCognitiveServicesFaceAPIExtensions class >> description [ ^ 'Inspector extensions for reasoning about the model.'
]
