"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser


"
Class {
	#name : #ManifestGToolkitDemoCognitiveServicesFaceAPI,
	#superclass : #PackageManifest,
	#category : #'GToolkit-Demo-CognitiveServices-FaceAPI'
}

{ #category : #'meta-data' }
ManifestGToolkitDemoCognitiveServicesFaceAPI class >> description [ ^ 'An object-oriented model for representing faces and pictures.'
]
