"
I am a target for PrioritySlideshow dropdown actions appearing in the hamburger menu of a slideshow

To use me as a target, define an action as a method in the slideshow, or as an extension method in `PrioritySlideshow`, with me as a `target:`.

"
Class {
	#name : #PrioritySlideshowActionTarget,
	#superclass : #GtPhlowActionUniqueTarget,
	#category : #'GToolkit-Demo-Slideshows-Action Targets'
}
