wikipedia - json text
jsonTextFacesEinsteinHabichtSolovine1280px
	^ '[
	{
		"faceId" : "585f743c-d91a-419c-a128-ba182c92c0af",
		"faceRectangle" : {
			"width" : 100,
			"height" : 100,
			"top" : 320,
			"left" : 860
		},
		"faceLandmarks" : {
			"noseRootRight" : {
				"x" : 912.4,
				"y" : 347.8
			},
			"eyeLeftTop" : {
				"x" : 887.4,
				"y" : 345.3
			},
			"eyebrowLeftInner" : {
				"x" : 897.1,
				"y" : 340.6
			},
			"upperLipTop" : {
				"x" : 911.1,
				"y" : 392.4
			},
			"noseRightAlarOutTip" : {
				"x" : 921.5,
				"y" : 374.2
			},
			"noseRootLeft" : {
				"x" : 900.6,
				"y" : 349.4
			},
			"noseTip" : {
				"x" : 907.2,
				"y" : 373.9
			},
			"pupilLeft" : {
				"x" : 888.1,
				"y" : 348.5
			},
			"mouthRight" : {
				"x" : 931.5,
				"y" : 393.9
			},
			"pupilRight" : {
				"x" : 929.6,
				"y" : 344.3
			},
			"eyeRightInner" : {
				"x" : 922.0,
				"y" : 346.2
			},
			"noseRightAlarTop" : {
				"x" : 916.2,
				"y" : 365.0
			},
			"eyeRightBottom" : {
				"x" : 929.7,
				"y" : 349.3
			},
			"eyeLeftOuter" : {
				"x" : 881.7,
				"y" : 350.7
			},
			"eyebrowRightOuter" : {
				"x" : 944.3,
				"y" : 336.7
			},
			"eyeLeftInner" : {
				"x" : 895.1,
				"y" : 348.9
			},
			"underLipBottom" : {
				"x" : 912.5,
				"y" : 402.6
			},
			"eyebrowRightInner" : {
				"x" : 913.1,
				"y" : 337.5
			},
			"eyeLeftBottom" : {
				"x" : 888.7,
				"y" : 352.8
			},
			"eyeRightTop" : {
				"x" : 928.7,
				"y" : 341.4
			},
			"noseLeftAlarOutTip" : {
				"x" : 895.8,
				"y" : 377.1
			},
			"upperLipBottom" : {
				"x" : 911.4,
				"y" : 396.0
			},
			"mouthLeft" : {
				"x" : 894.9,
				"y" : 396.1
			},
			"eyeRightOuter" : {
				"x" : 936.3,
				"y" : 344.9
			},
			"underLipTop" : {
				"x" : 911.4,
				"y" : 397.1
			},
			"eyebrowLeftOuter" : {
				"x" : 870.7,
				"y" : 346.5
			},
			"noseLeftAlarTop" : {
				"x" : 900.3,
				"y" : 366.8
			}
		},
		"faceAttributes" : {
			"facialHair" : {
				"beard" : 0.2,
				"moustache" : 0.8,
				"sideburns" : 0.1
			},
			"age" : 40.1,
			"smile" : 0.0,
			"gender" : "male",
			"accessories" : [ ],
			"headPose" : {
				"yaw" : -9.2,
				"pitch" : 0.0,
				"roll" : -5.3
			},
			"occlusion" : {
				"foreheadOccluded" : false,
				"eyeOccluded" : false,
				"mouthOccluded" : false
			},
			"blur" : {
				"blurLevel" : "medium",
				"value" : 0.28
			},
			"emotion" : {
				"neutral" : 1.0,
				"surprise" : 0.0,
				"contempt" : 0.0,
				"happiness" : 0.0,
				"anger" : 0.0,
				"sadness" : 0.0,
				"disgust" : 0.0,
				"fear" : 0.0
			},
			"noise" : {
				"noiseLevel" : "medium",
				"value" : 0.58
			},
			"glasses" : "NoGlasses",
			"exposure" : {
				"value" : 0.63,
				"exposureLevel" : "goodExposure"
			},
			"hair" : {
				"invisible" : false,
				"bald" : 0.0,
				"hairColor" : [
					{
						"color" : "brown",
						"confidence" : 0.98
					},
					{
						"color" : "black",
						"confidence" : 0.96
					},
					{
						"color" : "gray",
						"confidence" : 0.3
					},
					{
						"color" : "other",
						"confidence" : 0.26
					},
					{
						"color" : "red",
						"confidence" : 0.13
					},
					{
						"color" : "blond",
						"confidence" : 0.04
					}
				]
			},
			"makeup" : {
				"eyeMakeup" : false,
				"lipMakeup" : false
			}
		}
	},
	{
		"faceId" : "4867b8c7-1b19-494c-9e38-9d87ad8301ac",
		"faceRectangle" : {
			"width" : 99,
			"height" : 99,
			"top" : 313,
			"left" : 279
		},
		"faceLandmarks" : {
			"noseRootRight" : {
				"x" : 335.1,
				"y" : 340.8
			},
			"eyeLeftTop" : {
				"x" : 305.9,
				"y" : 335.8
			},
			"eyebrowLeftInner" : {
				"x" : 319.7,
				"y" : 329.1
			},
			"upperLipTop" : {
				"x" : 331.3,
				"y" : 379.8
			},
			"noseRightAlarOutTip" : {
				"x" : 344.1,
				"y" : 363.9
			},
			"noseRootLeft" : {
				"x" : 324.2,
				"y" : 341.0
			},
			"noseTip" : {
				"x" : 334.0,
				"y" : 361.6
			},
			"pupilLeft" : {
				"x" : 307.2,
				"y" : 338.3
			},
			"mouthRight" : {
				"x" : 345.9,
				"y" : 387.6
			},
			"pupilRight" : {
				"x" : 347.0,
				"y" : 339.4
			},
			"eyeRightInner" : {
				"x" : 340.4,
				"y" : 340.2
			},
			"noseRightAlarTop" : {
				"x" : 340.3,
				"y" : 356.1
			},
			"eyeRightBottom" : {
				"x" : 347.0,
				"y" : 342.9
			},
			"eyeLeftOuter" : {
				"x" : 299.1,
				"y" : 340.5
			},
			"eyebrowRightOuter" : {
				"x" : 360.7,
				"y" : 332.7
			},
			"eyeLeftInner" : {
				"x" : 313.7,
				"y" : 339.8
			},
			"underLipBottom" : {
				"x" : 330.5,
				"y" : 393.8
			},
			"eyebrowRightInner" : {
				"x" : 337.0,
				"y" : 330.0
			},
			"eyeLeftBottom" : {
				"x" : 306.0,
				"y" : 341.8
			},
			"eyeRightTop" : {
				"x" : 347.1,
				"y" : 336.9
			},
			"noseLeftAlarOutTip" : {
				"x" : 316.5,
				"y" : 364.5
			},
			"upperLipBottom" : {
				"x" : 330.8,
				"y" : 384.7
			},
			"mouthLeft" : {
				"x" : 309.0,
				"y" : 387.6
			},
			"eyeRightOuter" : {
				"x" : 353.7,
				"y" : 341.2
			},
			"underLipTop" : {
				"x" : 330.8,
				"y" : 388.9
			},
			"eyebrowLeftOuter" : {
				"x" : 288.0,
				"y" : 332.3
			},
			"noseLeftAlarTop" : {
				"x" : 321.6,
				"y" : 356.7
			}
		},
		"faceAttributes" : {
			"facialHair" : {
				"beard" : 0.2,
				"moustache" : 0.8,
				"sideburns" : 0.2
			},
			"age" : 48.9,
			"smile" : 0.0,
			"gender" : "male",
			"accessories" : [ ],
			"headPose" : {
				"yaw" : 15.4,
				"pitch" : 0.0,
				"roll" : -2.1
			},
			"occlusion" : {
				"foreheadOccluded" : false,
				"eyeOccluded" : false,
				"mouthOccluded" : false
			},
			"blur" : {
				"blurLevel" : "low",
				"value" : 0.06
			},
			"emotion" : {
				"neutral" : 0.996,
				"surprise" : 0.0,
				"contempt" : 0.001,
				"happiness" : 0.0,
				"anger" : 0.001,
				"sadness" : 0.002,
				"disgust" : 0.0,
				"fear" : 0.0
			},
			"noise" : {
				"noiseLevel" : "high",
				"value" : 0.72
			},
			"glasses" : "NoGlasses",
			"exposure" : {
				"value" : 0.6,
				"exposureLevel" : "goodExposure"
			},
			"hair" : {
				"invisible" : false,
				"bald" : 0.01,
				"hairColor" : [
					{
						"color" : "black",
						"confidence" : 0.87
					},
					{
						"color" : "brown",
						"confidence" : 0.81
					},
					{
						"color" : "gray",
						"confidence" : 0.56
					},
					{
						"color" : "other",
						"confidence" : 0.46
					},
					{
						"color" : "red",
						"confidence" : 0.21
					},
					{
						"color" : "blond",
						"confidence" : 0.11
					}
				]
			},
			"makeup" : {
				"eyeMakeup" : false,
				"lipMakeup" : false
			}
		}
	},
	{
		"faceId" : "9f6975e3-8110-44cd-aff9-06c502af3ff2",
		"faceRectangle" : {
			"width" : 92,
			"height" : 92,
			"top" : 172,
			"left" : 622
		},
		"faceLandmarks" : {
			"noseRootRight" : {
				"x" : 673.8,
				"y" : 199.8
			},
			"eyeLeftTop" : {
				"x" : 642.4,
				"y" : 197.3
			},
			"eyebrowLeftInner" : {
				"x" : 657.8,
				"y" : 192.6
			},
			"upperLipTop" : {
				"x" : 671.3,
				"y" : 236.3
			},
			"noseRightAlarOutTip" : {
				"x" : 683.5,
				"y" : 219.5
			},
			"noseRootLeft" : {
				"x" : 661.8,
				"y" : 201.0
			},
			"noseTip" : {
				"x" : 671.2,
				"y" : 220.5
			},
			"pupilLeft" : {
				"x" : 642.6,
				"y" : 199.2
			},
			"mouthRight" : {
				"x" : 687.4,
				"y" : 237.3
			},
			"pupilRight" : {
				"x" : 684.9,
				"y" : 195.2
			},
			"eyeRightInner" : {
				"x" : 680.0,
				"y" : 197.3
			},
			"noseRightAlarTop" : {
				"x" : 679.2,
				"y" : 213.1
			},
			"eyeRightBottom" : {
				"x" : 686.2,
				"y" : 197.5
			},
			"eyeLeftOuter" : {
				"x" : 635.7,
				"y" : 200.9
			},
			"eyebrowRightOuter" : {
				"x" : 701.2,
				"y" : 187.0
			},
			"eyeLeftInner" : {
				"x" : 650.5,
				"y" : 199.5
			},
			"underLipBottom" : {
				"x" : 672.8,
				"y" : 247.1
			},
			"eyebrowRightInner" : {
				"x" : 673.4,
				"y" : 191.3
			},
			"eyeLeftBottom" : {
				"x" : 643.2,
				"y" : 202.4
			},
			"eyeRightTop" : {
				"x" : 685.1,
				"y" : 193.5
			},
			"noseLeftAlarOutTip" : {
				"x" : 657.7,
				"y" : 223.0
			},
			"upperLipBottom" : {
				"x" : 671.9,
				"y" : 239.8
			},
			"mouthLeft" : {
				"x" : 652.0,
				"y" : 240.4
			},
			"eyeRightOuter" : {
				"x" : 691.8,
				"y" : 195.1
			},
			"underLipTop" : {
				"x" : 671.7,
				"y" : 241.6
			},
			"eyebrowLeftOuter" : {
				"x" : 624.2,
				"y" : 196.4
			},
			"noseLeftAlarTop" : {
				"x" : 660.4,
				"y" : 216.0
			}
		},
		"faceAttributes" : {
			"facialHair" : {
				"beard" : 0.6,
				"moustache" : 0.6,
				"sideburns" : 0.1
			},
			"age" : 41.1,
			"smile" : 0.001,
			"gender" : "male",
			"accessories" : [ ],
			"headPose" : {
				"yaw" : 5.8,
				"pitch" : 0.0,
				"roll" : -7.8
			},
			"occlusion" : {
				"foreheadOccluded" : false,
				"eyeOccluded" : false,
				"mouthOccluded" : false
			},
			"blur" : {
				"blurLevel" : "medium",
				"value" : 0.44
			},
			"emotion" : {
				"neutral" : 0.996,
				"surprise" : 0.0,
				"contempt" : 0.002,
				"happiness" : 0.001,
				"anger" : 0.0,
				"sadness" : 0.0,
				"disgust" : 0.0,
				"fear" : 0.0
			},
			"noise" : {
				"noiseLevel" : "high",
				"value" : 1.0
			},
			"glasses" : "NoGlasses",
			"exposure" : {
				"value" : 0.61,
				"exposureLevel" : "goodExposure"
			},
			"hair" : {
				"invisible" : false,
				"bald" : 0.01,
				"hairColor" : [
					{
						"color" : "brown",
						"confidence" : 0.98
					},
					{
						"color" : "black",
						"confidence" : 0.92
					},
					{
						"color" : "gray",
						"confidence" : 0.46
					},
					{
						"color" : "other",
						"confidence" : 0.25
					},
					{
						"color" : "red",
						"confidence" : 0.14
					},
					{
						"color" : "blond",
						"confidence" : 0.03
					}
				]
			},
			"makeup" : {
				"eyeMakeup" : false,
				"lipMakeup" : false
			}
		}
	}
]'