"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser


"
Class {
	#name : #ManifestGToolkitDemoCognitiveServicesFaceAPIUI,
	#superclass : #PackageManifest,
	#category : #'GToolkit-Demo-CognitiveServices-FaceAPI-UI'
}

{ #category : #'meta-data' }
ManifestGToolkitDemoCognitiveServicesFaceAPIUI class >> description [ ^ 'An implementation of a gallery that highlights the position of faces inside pictures.'
]
