"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser


"
Class {
	#name : #ManifestGToolkitDemoCognitiveServicesFaceAPIExamples,
	#superclass : #PackageManifest,
	#category : #'GToolkit-Demo-CognitiveServices-FaceAPI-Examples'
}

{ #category : #'meta-data' }
ManifestGToolkitDemoCognitiveServicesFaceAPIExamples class >> description [ ^ 'Example data for building pictures and faces.'
]
